name: Build and Release Codex v1.0.3

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-15, windows-latest]
        include:
          - os: ubuntu-latest
            platform: linux
          - os: macos-15
            platform: macos
          - os: windows-latest
            platform: windows
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm ci
      - name: Build Universal Package
        run: npm run make
        env:
          # Force universal builds for all architectures
          ELECTRON_FORGE_ARCH: "x64,arm64"
      - name: Publish to GitHub Releases
        run: npm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
